# Generated by Django 5.2.13 on 2026-05-13 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_ticket_ai_category_ticket_ai_priority_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='ai_category',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='ai_priority',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='ai_sentiment',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='ai_summary',
        ),
    ]
